name: test
channels:
  - conda-forge
dependencies:
  - python=3.8
  - psutil
  - anaconda-client
  - conda-build
  - mamba
  - pytest
  - pytest-cov
  - check-manifest
  - pip 
  - setuptools 
  - twine
